{"error": {
  "code": 400,
  "context": "Test file ExDTest2.json",
  "details": [{
    "code": "Exception",
    "message": "top level exception thrown by exception test when course string ran out"
  }],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 121",
    "    TestExceptions.java: sampleMethod3: 116",
    "    TestExceptions.java: callHigher: 131",
    "    TestExceptions.java: testExceptionStackTrace: 178"
  ]
}}