{"error": {
  "code": 400,
  "context": "Test file ExTest2.json for course 3",
  "details": [{
    "code": "Exception",
    "message": "top level exception thrown by exception test when course string ran out"
  }],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 82",
    "    TestExceptions.java: sampleMethod3: 77",
    "    TestExceptions.java: callHigher: 92",
    "    TestExceptions.java: testExceptionStackTrace: 146"
  ]
}}