{"error": {
  "code": 400,
  "context": "Test file ExTest2.json for course 3",
  "details": [{
    "code": "Exception",
    "message": "top level exception thrown by exception test when course string ran out"
  }],
  "innerError": {},
  "stack": [
    "top level exception thrown by exception test when course string ran out",
    "    TestExceptions.java: callHigher: 86",
    "    TestExceptions.java: sampleMethod3: 81",
    "    TestExceptions.java: callHigher: 96",
    "    TestExceptions.java: runCourse: 146",
    "    TestExceptions.java: runTests: 37",
    "    TestRecorderText.java: parseArgsRunTests: 637",
    "    TestExceptions.java: main: 184"
  ]
}}